### ISSUE TITLE
When attempting to build libgphoto2 it fails 

### ISSUE THREAD

**Issue by glyons** [gonzalo/gphoto2-updater#11]
When attempting to build libgphoto2 it fails 

Makefile :902 recipe for target 'usb1_la-libusb1.lo' failed 
Make 1004 recipe for target 'install-recursive' failed.
 

any ideas ?

Thanks
Gavin

**Comment by OutdoorMe** [comment]
glyons thank you very much for the Info you posted about the older libusbx_1.0.11.orig.tar.bz2 it fixed my problem compiling libgphoto2 / gphoto2 on Raspbian 

With libusbx 1.0.17 / 1.0.18 I received this error:

libtool: compile:  gcc -DHAVE_CONFIG_H -I. -DLOCALEDIR=\"/usr/local/share/locale\" -DIOLIBS=\"/usr/local/lib/libgphoto2_port/0.12.0\" -D_GPHOTO2_INTERNAL_CODE -I. -I/usr/local/include/libusb-1.0 -g -O2 -Wall -Wmissing-declarations -Wmissing-prototypes -MT usb1_la-libusb1.lo -MD -MP -MF .deps/usb1_la-libusb1.Tpo -c libusb1/libusb1.c  -fPIC -DPIC -o .libs/usb1_la-libusb1.o
libusb1/libusb1.c:70:20: error: static declaration of 'libusb_strerror' follows non-static declaration
/usr/local/include/libusb-1.0/libusb.h:1307:26: note: previous declaration of 'libusb_strerror' was here
Makefile:902: recipe for target 'usb1_la-libusb1.lo' failed
make[4]: *** [usb1_la-libusb1.lo] Error 1

Going back to libusbx_1.0.11.orig.tar.bz2 fixed my problem and the latest gphoto2-2.5.7 and gphoto2-2.5.6 compiled successfully.

I have configured the libusbx with
./configure --prefix=/usr
because I found that I already had the file /usr/include/libusb-1.0/libusb.h available in my Raspbian installed from some package ...

**Comment by gonzalo** [comment]
seems to be some problem with libusbx_1.0.17 currently unavailable in official debian repositories. new version of script released please test it.
